local BinaryUI=require(path.To.BinaryUI)
local window=BinaryUI:CreateWindow({Title="BinaryUI Showcase",Subtitle="Obsidian Neon"})
local tab=window:AddTab({Name="Main"})
local section=tab:AddSection({Name="Controls"})
section:AddLabel({Text="Modular controls with isolated callbacks."})
section:AddButton({Name="Test callback",Callback=function() print("BinaryUI callback executed safely.") end})
section:AddToggle({Name="Feature",Default=false,Callback=function(v) print("Feature:",v) end})
section:AddSlider({Name="Power",Min=0,Max=100,Default=50,Callback=function(v) print("Power:",v) end})
section:AddDropdown({Name="Mode",Options={"Low","Medium","High"},Default="Medium",Callback=function(v) print("Mode:",v) end})
section:AddTextbox({Placeholder="Type something...",Callback=function(v) print("Input:",v) end})
section:AddKeybind({Name="Toggle UI",Key=Enum.KeyCode.RightShift,Callback=function() print("Keybind pressed") end})
